volumes:
  api-gft-data:
    external: true
  pg-admin:
    external: true

services:
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://gft-user:${POSTGRES_PASSWORD}@db/gft-data
      WAIT_HOSTS: db:5432
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    volumes:
      - ./sample_service:/app

  ghi:
    image: node:lts-bullseye
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
      CHOKIDAR_USEPOLLING: true # create-ui-app <= 5.x
      WATCHPACK_POLLING: true # create-ui-app >= 5.x

  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: gft-user
      POSTGRES_DB: gft-data
    ports:
      - "15432:5432"
    volumes:
      - api-gft-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: 1
